version = 0.1
[default.deploy.parameters]
stack_name = "firehose-transformation-sam"
resolve_s3 = true
s3_prefix = "firehose-transformation-sam"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "EditedBucketName=\"firehose-transformation-edited\" RawBucketName=\"firehose-transformation-raw\""
image_repositories = []
